export type EditorCommand =
  | 'select-all'
  | 'clear-selection'
  | 'delete-selection'
  | 'group-selection'
  | 'ungroup-selection'
  | 'copy'
  | 'cut'
  | 'paste'
  | 'duplicate'
  | 'align-left'
  | 'align-center'
  | 'align-right'
  | 'align-top'
  | 'align-middle'
  | 'align-bottom'
  | 'distribute-horizontal'
  | 'distribute-vertical'
