export const PACKAGE_NAME = '@canvaskit/core'

export { DEFAULT_LAYER_ID, SCENE_VERSION } from './model.js'
export type { CanvasConnector, CanvasEdge, CanvasGroup, CanvasLayer, CanvasNode, CanvasScene, CircleNode, ConnectorRouting, CreateCircleInput, CreateConnectorInput, CreateEdgeInput, CreateGroupInput, CreateRectangleInput, CreateTextInput, NodePort, PortDirection, RectangleNode, TextNode } from './model.js'
export { addCircle, addConnector, addEdge, addGroup, addRectangle, addText, connectNodes, createScene, removeConnector, removeEdge, translateNode } from './scene.js'
export { addLayer, groupNodes, interactiveNodesInRenderOrder, isNodeInteractive, moveNodesToLayer, projectVisibleDocument, removeLayer, reorderLayer, reorderNodeInLayer, setLayerLocked, setLayerVisibility, ungroupNodes } from './document.js'
export type { VisibleDocumentProjection } from './document.js'
export { copySelection, pasteSelection, removeSelection } from './clipboard.js'
export type { PasteSelectionResult, SceneClipboard } from './clipboard.js'
export type { EditorCommand } from './editor-command.js'
export { hitTestConnector, hitTestEdge, nodeCenter } from './graph-interaction.js'
export { exportScene, importScene, InvalidSceneError, loadScene, serializeScene, UnsupportedSceneVersionError } from './serialization.js'
export { migrateScene } from './migrations.js'
export { ViewportController } from './viewport.js'
export { CanvasKit } from './canvas-kit.js'
export type { CanvasKitOptions, CanvasPointerEvent, CanvasPointerEventType, CanvasPointerModifiers, MarqueeSelectionOptions } from './canvas-kit.js'
export type { SceneListener } from './scene-subscription.js'
export type { CanvasPlugin, Renderer } from './plugin.js'
export { EdgeRegistry, NodeRegistry } from './registry.js'
export type { NamedDefinition } from './registry.js'
export { HistoryController } from './history.js'
export type { SceneCommand } from './history.js'
export { attachPointerInput } from './pointer-input.js'
export { SelectionController } from './selection.js'
export type { SelectionMode } from './selection.js'
export { hitTestNode, moveNodes, nodesInRect } from './interaction.js'
export type { MarqueeMode } from './interaction.js'
export { attachKeyboardInput } from './keyboard-input.js'
export { snapPointToGrid } from './grid.js'
export { nodeBounds } from './bounds.js'
export { deriveNodePorts, findNodePort } from './ports.js'
export { ConnectorController } from './connector.js'
export type { ConnectorEndpoint, ReconnectConnectorInput } from './connector.js'
export { TransformController, UnsupportedPersistentRotationError } from './transform.js'
export type { AlignmentAxis, DistributionAxis, TransformConstraints, TransformHandle, TransformOverlay } from './transform.js'
export { SpatialIndex } from './spatial-index.js'
