import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'CanvasKit',
  description: 'A TypeScript-first engine for interactive visual editors on an infinite canvas.',
  cleanUrls: true,
  // Planning and design artifacts remain in the repository, but are not part
  // of the publishable documentation surface.
  srcExclude: ['superpowers/**'],
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/getting-started' },
      { text: 'Transform tools', link: '/guides/transform-tools' },
      { text: 'Document & layers', link: '/guides/document-layers' },
      { text: 'Diagram toolkit', link: '/guides/diagram-toolkit' },
      { text: 'Smart layout', link: '/guides/smart-layout' },
      { text: 'Rich content', link: '/guides/rich-content-assets' },
      { text: 'Export & accessibility', link: '/guides/export-accessibility' },
      { text: 'Plugin platform', link: '/guides/plugin-platform' },
      { text: 'Editor workflow guide', link: '/guides/editor-workflow' },
      { text: 'API reference', link: '/api/core' },
      { text: 'Transform API', link: '/api/transform-tools' },
      { text: 'Document & layers API', link: '/api/document-layers' },
      { text: 'Diagram API', link: '/api/diagram-toolkit' },
      { text: 'Smart layout API', link: '/api/smart-layout' },
      { text: 'Rich content API', link: '/api/rich-content-assets' },
      { text: 'Export & accessibility API', link: '/api/export-accessibility' },
      { text: 'Plugin platform API', link: '/api/plugin-platform' },
      { text: 'Editor workflow API', link: '/api/editor-workflow' },
      { text: 'Examples', link: '/examples' },
      { text: 'V3 release', link: '/release-notes-v3' },
    ],
    sidebar: {
      '/api/': [
        {
          text: 'API reference',
          items: [
            { text: 'Geometry', link: '/api/geometry' },
            { text: 'Core', link: '/api/core' },
            { text: 'Transform tools', link: '/api/transform-tools' },
            { text: 'Document & layers', link: '/api/document-layers' },
            { text: 'Diagram toolkit', link: '/api/diagram-toolkit' },
            { text: 'Smart layout', link: '/api/smart-layout' },
            { text: 'Rich content & assets', link: '/api/rich-content-assets' },
            { text: 'Export & accessibility', link: '/api/export-accessibility' },
            { text: 'Plugin platform', link: '/api/plugin-platform' },
            { text: 'Editor workflow', link: '/api/editor-workflow' },
            { text: 'Canvas renderer', link: '/api/canvas' },
            { text: 'SVG renderer', link: '/api/svg' },
            { text: 'Official plugins', link: '/api/plugins' },
            { text: 'React', link: '/api/react' },
            { text: 'Vue', link: '/api/vue' },
          ],
        },
      ],
      '/': [
        {
          text: 'Guide',
          items: [
            { text: 'Getting started', link: '/getting-started' },
            { text: 'Transform tools', link: '/guides/transform-tools' },
            { text: 'Document & layers', link: '/guides/document-layers' },
            { text: 'Diagram toolkit', link: '/guides/diagram-toolkit' },
            { text: 'Smart layout', link: '/guides/smart-layout' },
            { text: 'Rich content & assets', link: '/guides/rich-content-assets' },
            { text: 'Export & accessibility', link: '/guides/export-accessibility' },
            { text: 'Plugin platform', link: '/guides/plugin-platform' },
            { text: 'Editor workflow', link: '/guides/editor-workflow' },
            { text: 'Examples', link: '/examples' },
            { text: 'Performance', link: '/performance' },
            { text: 'Plugins', link: '/plugins' },
            { text: 'Frameworks', link: '/frameworks' },
            { text: 'Nuxt and SSR', link: '/nuxt' },
            { text: 'Migrations', link: '/migrations' },
          ],
        },
        {
          text: 'Release readiness',
          items: [
            { text: 'CanvasKit 1.0.0', link: '/release-notes-v1' },
            { text: 'CanvasKit 2.0.0', link: '/release-notes-v2' },
            { text: 'CanvasKit 3.0.0', link: '/release-notes-v3' },
            { text: 'V3 professional diagram architecture', link: '/architecture/v3-professional-diagram-runtime' },
            { text: 'V3 release asset manifest', link: '/release-assets-v3' },
            { text: 'CanvasKit V2.0 transform tools', link: '/release-notes-v2' },
            { text: 'CanvasKit V2.2 document & layers', link: '/release-notes-v2-2' },
            { text: 'CanvasKit V2.3 diagram toolkit', link: '/release-notes-v2-3' },
            { text: 'V2.0 architecture', link: '/architecture/v2-transform-tools' },
            { text: 'V2.2 architecture', link: '/architecture/v2-document-layers' },
            { text: 'V2.3 architecture', link: '/architecture/v2-diagram-toolkit' },
            { text: 'V2.4 architecture', link: '/architecture/v2-smart-layout' },
            { text: 'V2.5 release notes', link: '/release-notes-v2-5' },
            { text: 'V2.6 release notes', link: '/release-notes-v2-6' },
            { text: 'V2.7 release notes', link: '/release-notes-v2-7' },
            { text: 'V2.5 architecture', link: '/architecture/v2-rich-content-assets' },
            { text: 'V2.6 architecture', link: '/architecture/v2-export-accessibility' },
            { text: 'V2.7 architecture', link: '/architecture/v2-plugin-platform' },
            { text: 'V2.0 release asset manifest', link: '/release-assets-v2' },
            { text: 'V2.2 release asset manifest', link: '/release-assets-v2-2' },
            { text: 'V2.3 release asset manifest', link: '/release-assets-v2-3' },
            { text: 'V2.4 release asset manifest', link: '/release-assets-v2-4' },
            { text: 'V2.5 release asset manifest', link: '/release-assets-v2-5' },
            { text: 'V2.6 release asset manifest', link: '/release-assets-v2-6' },
            { text: 'V2.7 release asset manifest', link: '/release-assets-v2-7' },
            { text: 'Upgrading to V1', link: '/upgrading-to-v1' },
            { text: 'Upgrading to V2', link: '/upgrading-to-v2' },
            { text: 'Upgrading to V3', link: '/upgrading-to-v3' },
            { text: 'API stability', link: '/api-stability' },
            { text: 'Release quality gates', link: '/release-quality' },
            { text: 'V1 RC checklist', link: '/release-candidate-checklist' },
            { text: 'Release checklist', link: '/release-checklist' },
            { text: 'Publishing runbook', link: '/publishing' },
            { text: 'RC feedback', link: '/rc-feedback' },
          ],
        },
      ],
    },
    search: { provider: 'local' },
  },
})
